kind: pipeline
type: docker
name: greeting

environment:
  GREETING_EN: hello

steps:
- name: en
  image: alpine
  commands:
  - echo $GREETING_EN
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde
