kind: pipeline
name: default

steps:
  - name: build
    image: node:current-alpine
    environment:
      NPMRC:
        from_secret: NPMRC    
    commands:   
      - echo -e "$NPMRC" > .npmrc
      - cat .npmrc
      - yarn
      - cd packages/uikit-react
      - yarn build
      - npm publish

