kind: pipeline
name: default

steps:
  - name: build
    image: node:current-alpine
    environment:
      NPMREGISTRY:
        from_secret: NPMREGISTRY    
    commands:   
      - npm config set registry $NPMREGISTRY
      - yarn
      - cd packages/uikit-react
      - yarn build
      - npm publish

