kind: pipeline
name: default

steps:
  - name: build
    image: node:current-alpine
    environment:
      NPMREGISTRY:
        from_secret: NPMREGISTRY
      NPMAUTHTOKEN:
        from_secret: NPMAUTHTOKEN
    commands:   
      - npm config set $NPMREGISTRY
      - npm config set $NPMAUTHTOKEN
      - yarn
      - cd packages/uikit-react
      - yarn build
      - npm publish

